///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HBTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddingToWishlist recording.
    /// </summary>
    [TestModule("958792de-9953-4d77-b98b-caff963bd8a7", ModuleType.Recording, 1)]
    public partial class AddingToWishlist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HBTestRepository repository.
        /// </summary>
        public static HBTestRepository repo = HBTestRepository.Instance;

        static AddingToWishlist instance = new AddingToWishlist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddingToWishlist()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddingToWishlist Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainPage.FavoritesList.BtnFavorites' at 17;9.", repo.MainPage.FavoritesList.BtnFavoritesInfo, new RecordItemIndex(0));
            repo.MainPage.FavoritesList.BtnFavorites.Click("17;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                        Ürün listenize eklendi.\n                    ') on item 'MainPage.FavoritesList.FavoritesNotification'.", repo.MainPage.FavoritesList.FavoritesNotificationInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainPage.FavoritesList.FavoritesNotificationInfo, "InnerText", "\n                        Ürün listenize eklendi.\n                    ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainPage.FavoritesList.CloseNotification' at 11;4.", repo.MainPage.FavoritesList.CloseNotificationInfo, new RecordItemIndex(2));
            repo.MainPage.FavoritesList.CloseNotification.Click("11;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
