///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HBTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HBTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bb970b4c-a5b4-4b82-b445-0fe51f2dbcca")]
    public partial class HBTestRepository : RepoGenBaseFolder
    {
        static HBTestRepository instance = new HBTestRepository();
        HBTestRepositoryFolders.MainPageAppFolder _mainpage;
        HBTestRepositoryFolders.CartPageAppFolder _cartpage;
        HBTestRepositoryFolders.LoginPageAppFolder _loginpage;
        HBTestRepositoryFolders.ReloadLoginPageAppFolder _reloadloginpage;

        /// <summary>
        /// Gets the singleton class instance representing the HBTestRepository element repository.
        /// </summary>
        [RepositoryFolder("bb970b4c-a5b4-4b82-b445-0fe51f2dbcca")]
        public static HBTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HBTestRepository() 
            : base("HBTestRepository", "/", null, 0, false, "bb970b4c-a5b4-4b82-b445-0fe51f2dbcca", ".\\RepositoryImages\\HBTestRepositorybb970b4c.rximgres")
        {
            _mainpage = new HBTestRepositoryFolders.MainPageAppFolder(this);
            _cartpage = new HBTestRepositoryFolders.CartPageAppFolder(this);
            _loginpage = new HBTestRepositoryFolders.LoginPageAppFolder(this);
            _reloadloginpage = new HBTestRepositoryFolders.ReloadLoginPageAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bb970b4c-a5b4-4b82-b445-0fe51f2dbcca")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainPage folder.
        /// </summary>
        [RepositoryFolder("0bce88dc-8814-4a00-af61-c62de9b53c4b")]
        public virtual HBTestRepositoryFolders.MainPageAppFolder MainPage
        {
            get { return _mainpage; }
        }

        /// <summary>
        /// The CartPage folder.
        /// </summary>
        [RepositoryFolder("37fb3645-05db-4947-9adc-5cfd4647ea85")]
        public virtual HBTestRepositoryFolders.CartPageAppFolder CartPage
        {
            get { return _cartpage; }
        }

        /// <summary>
        /// The LoginPage folder.
        /// </summary>
        [RepositoryFolder("3c62336d-dc6d-4b37-80ae-342503924fd0")]
        public virtual HBTestRepositoryFolders.LoginPageAppFolder LoginPage
        {
            get { return _loginpage; }
        }

        /// <summary>
        /// The ReloadLoginPage folder.
        /// </summary>
        [RepositoryFolder("2e9fd513-b0d0-4a2d-a5b4-5093b8b17379")]
        public virtual HBTestRepositoryFolders.ReloadLoginPageAppFolder ReloadLoginPage
        {
            get { return _reloadloginpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class HBTestRepositoryFolders
    {
        /// <summary>
        /// The MainPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("0bce88dc-8814-4a00-af61-c62de9b53c4b")]
        public partial class MainPageAppFolder : RepoGenBaseFolder
        {
            HBTestRepositoryFolders.CartAddAndGoFolder _cartaddandgo;
            HBTestRepositoryFolders.SearchingItemFolder _searchingitem;
            HBTestRepositoryFolders.LoginFolder _login;
            HBTestRepositoryFolders.FavoritesListFolder _favoriteslist;
            RepoItemInfo _btnacceptcookiesInfo;

            /// <summary>
            /// Creates a new MainPage  folder.
            /// </summary>
            public MainPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainPage", "/dom[@domain='www.hepsiburada.com']", parentFolder, 30000, null, false, "0bce88dc-8814-4a00-af61-c62de9b53c4b", "")
            {
                _cartaddandgo = new HBTestRepositoryFolders.CartAddAndGoFolder(this);
                _searchingitem = new HBTestRepositoryFolders.SearchingItemFolder(this);
                _login = new HBTestRepositoryFolders.LoginFolder(this);
                _favoriteslist = new HBTestRepositoryFolders.FavoritesListFolder(this);
                _btnacceptcookiesInfo = new RepoItemInfo(this, "BtnAcceptCookies", ".//button[#'onetrust-accept-btn-handler']", ".//button[#'onetrust-accept-btn-handler']", 30000, null, "3285b6ef-e91f-48ea-9fe2-269f532a33f8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0bce88dc-8814-4a00-af61-c62de9b53c4b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0bce88dc-8814-4a00-af61-c62de9b53c4b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnAcceptCookies item.
            /// </summary>
            [RepositoryItem("3285b6ef-e91f-48ea-9fe2-269f532a33f8")]
            public virtual Ranorex.ButtonTag BtnAcceptCookies
            {
                get
                {
                    return _btnacceptcookiesInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnAcceptCookies item info.
            /// </summary>
            [RepositoryItemInfo("3285b6ef-e91f-48ea-9fe2-269f532a33f8")]
            public virtual RepoItemInfo BtnAcceptCookiesInfo
            {
                get
                {
                    return _btnacceptcookiesInfo;
                }
            }

            /// <summary>
            /// The CartAddAndGo folder.
            /// </summary>
            [RepositoryFolder("ddec5af9-2253-47dc-b065-0c85ed373af0")]
            public virtual HBTestRepositoryFolders.CartAddAndGoFolder CartAddAndGo
            {
                get { return _cartaddandgo; }
            }

            /// <summary>
            /// The SearchingItem folder.
            /// </summary>
            [RepositoryFolder("a61a0307-50b8-4f4a-9608-19f0d7032926")]
            public virtual HBTestRepositoryFolders.SearchingItemFolder SearchingItem
            {
                get { return _searchingitem; }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("8e26a75d-d27c-42e6-8e82-c65189096d23")]
            public virtual HBTestRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The FavoritesList folder.
            /// </summary>
            [RepositoryFolder("7ffa0f9b-687d-4a68-a0ac-17712c4bad29")]
            public virtual HBTestRepositoryFolders.FavoritesListFolder FavoritesList
            {
                get { return _favoriteslist; }
            }
        }

        /// <summary>
        /// The CartAddAndGoFolder folder.
        /// </summary>
        [RepositoryFolder("ddec5af9-2253-47dc-b065-0c85ed373af0")]
        public partial class CartAddAndGoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _gotocartInfo;

            /// <summary>
            /// Creates a new CartAddAndGo  folder.
            /// </summary>
            public CartAddAndGoFolder(RepoGenBaseFolder parentFolder) :
                    base("CartAddAndGo", "", parentFolder, 0, null, false, "ddec5af9-2253-47dc-b065-0c85ed373af0", "")
            {
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", ".//button[#'addToCart']", ".//button[#'addToCart']", 30000, null, "530aadc3-a89d-4c56-be2f-cbbf21f34ff0");
                _gotocartInfo = new RepoItemInfo(this, "GoToCart", "body/div[6]/div/div/div/div/div/div/div[1]/div/div[1]/div/div[2]/button[@innertext='Sepete git']", ".//button[@innertext='Sepete git']", 30000, null, "d38d8555-7e14-4a4b-9212-a9888d553dea");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ddec5af9-2253-47dc-b065-0c85ed373af0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("530aadc3-a89d-4c56-be2f-cbbf21f34ff0")]
            public virtual Ranorex.ButtonTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("530aadc3-a89d-4c56-be2f-cbbf21f34ff0")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The GoToCart item.
            /// </summary>
            [RepositoryItem("d38d8555-7e14-4a4b-9212-a9888d553dea")]
            public virtual Ranorex.ButtonTag GoToCart
            {
                get
                {
                    return _gotocartInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The GoToCart item info.
            /// </summary>
            [RepositoryItemInfo("d38d8555-7e14-4a4b-9212-a9888d553dea")]
            public virtual RepoItemInfo GoToCartInfo
            {
                get
                {
                    return _gotocartInfo;
                }
            }
        }

        /// <summary>
        /// The SearchingItemFolder folder.
        /// </summary>
        [RepositoryFolder("a61a0307-50b8-4f4a-9608-19f0d7032926")]
        public partial class SearchingItemFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchboxInfo;
            RepoItemInfo _btnaraInfo;
            RepoItemInfo _itemlinkInfo;
            RepoItemInfo _productnameInfo;

            /// <summary>
            /// Creates a new SearchingItem  folder.
            /// </summary>
            public SearchingItemFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchingItem", "", parentFolder, 0, null, false, "a61a0307-50b8-4f4a-9608-19f0d7032926", "")
            {
                _searchboxInfo = new RepoItemInfo(this, "SearchBox", ".//div[#'container']/div/div/div[4]/div[5]/div/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div/div/div/div[1]", ".//div[#'container']/div/div/div[4]/div[5]/div/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div/div/div/div[1]", 30000, null, "5691b5d0-81e4-4165-9de3-9a9a5a031f85");
                _btnaraInfo = new RepoItemInfo(this, "btnARA", ".//div[#'container']/div/div/div[4]/div[5]/div/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div//div[@innertext='ARA']", ".//div[#'container']//div[@innertext='ARA']", 30000, null, "7a8b850d-0141-40fc-bb28-015e6ddc67be");
                _itemlinkInfo = new RepoItemInfo(this, "ItemLink", ".//div[#'containerSelectorFocus']/div[2]/div[2]/div[4]/div//ul/li[1]/?/?/a[@title='Cmt Mini Tornavida 31''li']/div[2]/div[1]/h3[@innertext=' Mini Tornavida 31''li']", ".//div[#'containerSelectorFocus']//h3[@innertext=' Mini Tornavida 31''li']", 30000, null, "62f74c86-8130-4745-9f1d-4a761dcc6d5c");
                _productnameInfo = new RepoItemInfo(this, "ProductName", ".//h1[#'product-name']", ".//h1[#'product-name']", 30000, null, "7d3c68e2-8ca9-46a9-a8d8-64675acd9ec6");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a61a0307-50b8-4f4a-9608-19f0d7032926")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchBox item.
            /// </summary>
            [RepositoryItem("5691b5d0-81e4-4165-9de3-9a9a5a031f85")]
            public virtual Ranorex.DivTag SearchBox
            {
                get
                {
                    return _searchboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SearchBox item info.
            /// </summary>
            [RepositoryItemInfo("5691b5d0-81e4-4165-9de3-9a9a5a031f85")]
            public virtual RepoItemInfo SearchBoxInfo
            {
                get
                {
                    return _searchboxInfo;
                }
            }

            /// <summary>
            /// The btnARA item.
            /// </summary>
            [RepositoryItem("7a8b850d-0141-40fc-bb28-015e6ddc67be")]
            public virtual Ranorex.DivTag btnARA
            {
                get
                {
                    return _btnaraInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btnARA item info.
            /// </summary>
            [RepositoryItemInfo("7a8b850d-0141-40fc-bb28-015e6ddc67be")]
            public virtual RepoItemInfo btnARAInfo
            {
                get
                {
                    return _btnaraInfo;
                }
            }

            /// <summary>
            /// The ItemLink item.
            /// </summary>
            [RepositoryItem("62f74c86-8130-4745-9f1d-4a761dcc6d5c")]
            public virtual Ranorex.H3Tag ItemLink
            {
                get
                {
                    return _itemlinkInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The ItemLink item info.
            /// </summary>
            [RepositoryItemInfo("62f74c86-8130-4745-9f1d-4a761dcc6d5c")]
            public virtual RepoItemInfo ItemLinkInfo
            {
                get
                {
                    return _itemlinkInfo;
                }
            }

            /// <summary>
            /// The ProductName item.
            /// </summary>
            [RepositoryItem("7d3c68e2-8ca9-46a9-a8d8-64675acd9ec6")]
            public virtual Ranorex.H1Tag ProductName
            {
                get
                {
                    return _productnameInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The ProductName item info.
            /// </summary>
            [RepositoryItemInfo("7d3c68e2-8ca9-46a9-a8d8-64675acd9ec6")]
            public virtual RepoItemInfo ProductNameInfo
            {
                get
                {
                    return _productnameInfo;
                }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("8e26a75d-d27c-42e6-8e82-c65189096d23")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logintitleInfo;
            RepoItemInfo _loginlinkInfo;
            RepoItemInfo _myaccountInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "8e26a75d-d27c-42e6-8e82-c65189096d23", "")
            {
                _logintitleInfo = new RepoItemInfo(this, "LoginTitle", ".//div[#'myAccount']/?/?/span[@title='Giriş Yap']", ".//div[#'myAccount']/?/?/span[@title='Giriş Yap']", 30000, null, "f6c5a83c-1603-4a08-936b-c95182a08eb0");
                _loginlinkInfo = new RepoItemInfo(this, "LoginLink", ".//a[#'login']", ".//a[#'login']", 30000, null, "5c7ad4c5-70bf-4d2f-8a69-c7fb6e3e39c7");
                _myaccountInfo = new RepoItemInfo(this, "MyAccount", ".//div[#'myAccount']//span[@innertext='Hesabım']", ".//div[#'myAccount']//span[@innertext='Hesabım']", 30000, null, "e99b561b-c177-483b-8646-87a2616878e8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e26a75d-d27c-42e6-8e82-c65189096d23")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginTitle item.
            /// </summary>
            [RepositoryItem("f6c5a83c-1603-4a08-936b-c95182a08eb0")]
            public virtual Ranorex.SpanTag LoginTitle
            {
                get
                {
                    return _logintitleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LoginTitle item info.
            /// </summary>
            [RepositoryItemInfo("f6c5a83c-1603-4a08-936b-c95182a08eb0")]
            public virtual RepoItemInfo LoginTitleInfo
            {
                get
                {
                    return _logintitleInfo;
                }
            }

            /// <summary>
            /// The LoginLink item.
            /// </summary>
            [RepositoryItem("5c7ad4c5-70bf-4d2f-8a69-c7fb6e3e39c7")]
            public virtual Ranorex.ATag LoginLink
            {
                get
                {
                    return _loginlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LoginLink item info.
            /// </summary>
            [RepositoryItemInfo("5c7ad4c5-70bf-4d2f-8a69-c7fb6e3e39c7")]
            public virtual RepoItemInfo LoginLinkInfo
            {
                get
                {
                    return _loginlinkInfo;
                }
            }

            /// <summary>
            /// The MyAccount item.
            /// </summary>
            [RepositoryItem("e99b561b-c177-483b-8646-87a2616878e8")]
            public virtual Ranorex.SpanTag MyAccount
            {
                get
                {
                    return _myaccountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MyAccount item info.
            /// </summary>
            [RepositoryItemInfo("e99b561b-c177-483b-8646-87a2616878e8")]
            public virtual RepoItemInfo MyAccountInfo
            {
                get
                {
                    return _myaccountInfo;
                }
            }
        }

        /// <summary>
        /// The FavoritesListFolder folder.
        /// </summary>
        [RepositoryFolder("7ffa0f9b-687d-4a68-a0ac-17712c4bad29")]
        public partial class FavoritesListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnfavoritesInfo;
            RepoItemInfo _favoritesnotificationInfo;
            RepoItemInfo _closenotificationInfo;

            /// <summary>
            /// Creates a new FavoritesList  folder.
            /// </summary>
            public FavoritesListFolder(RepoGenBaseFolder parentFolder) :
                    base("FavoritesList", "", parentFolder, 0, null, false, "7ffa0f9b-687d-4a68-a0ac-17712c4bad29", "")
            {
                _btnfavoritesInfo = new RepoItemInfo(this, "BtnFavorites", ".//div[#'favoriteContainerInner']/div/div/div/div/div[1]/div[1]", ".//div[#'favoriteContainerInner']/div/div/div/div/div[1]/div[1]", 30000, null, "8d500d76-c261-4f95-bc70-571b9ee6cf53");
                _favoritesnotificationInfo = new RepoItemInfo(this, "FavoritesNotification", "body/div[9]//div[@innertext>'                        Ürün']", ".//div[@innertext>'                        Ürün']", 30000, null, "8a1fad16-c9f2-4b84-901f-778be3044327");
                _closenotificationInfo = new RepoItemInfo(this, "CloseNotification", "body/div[9]/div/div/div[3]/svg", "body/div[9]/div/div/div[3]/svg", 30000, null, "8ffcd933-6c28-4ec4-8b54-046ed3a44401");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ffa0f9b-687d-4a68-a0ac-17712c4bad29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnFavorites item.
            /// </summary>
            [RepositoryItem("8d500d76-c261-4f95-bc70-571b9ee6cf53")]
            public virtual Ranorex.DivTag BtnFavorites
            {
                get
                {
                    return _btnfavoritesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BtnFavorites item info.
            /// </summary>
            [RepositoryItemInfo("8d500d76-c261-4f95-bc70-571b9ee6cf53")]
            public virtual RepoItemInfo BtnFavoritesInfo
            {
                get
                {
                    return _btnfavoritesInfo;
                }
            }

            /// <summary>
            /// The FavoritesNotification item.
            /// </summary>
            [RepositoryItem("8a1fad16-c9f2-4b84-901f-778be3044327")]
            public virtual Ranorex.DivTag FavoritesNotification
            {
                get
                {
                    return _favoritesnotificationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FavoritesNotification item info.
            /// </summary>
            [RepositoryItemInfo("8a1fad16-c9f2-4b84-901f-778be3044327")]
            public virtual RepoItemInfo FavoritesNotificationInfo
            {
                get
                {
                    return _favoritesnotificationInfo;
                }
            }

            /// <summary>
            /// The CloseNotification item.
            /// </summary>
            [RepositoryItem("8ffcd933-6c28-4ec4-8b54-046ed3a44401")]
            public virtual Ranorex.SvgTag CloseNotification
            {
                get
                {
                    return _closenotificationInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The CloseNotification item info.
            /// </summary>
            [RepositoryItemInfo("8ffcd933-6c28-4ec4-8b54-046ed3a44401")]
            public virtual RepoItemInfo CloseNotificationInfo
            {
                get
                {
                    return _closenotificationInfo;
                }
            }
        }

        /// <summary>
        /// The CartPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("37fb3645-05db-4947-9adc-5cfd4647ea85")]
        public partial class CartPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemnameInfo;
            RepoItemInfo _btnremoveInfo;
            RepoItemInfo _removenotificationInfo;
            RepoItemInfo _btnremove2Info;

            /// <summary>
            /// Creates a new CartPage  folder.
            /// </summary>
            public CartPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPage", "/dom[@domain='checkout.hepsiburada.com']", parentFolder, 30000, null, false, "37fb3645-05db-4947-9adc-5cfd4647ea85", "")
            {
                _itemnameInfo = new RepoItemInfo(this, "ItemName", ".//section[#'onboarding_item_list']/div[2]/ul/li/div[1]//a[@innertext='Cmt Mini Tornavida 31''li']", ".//section[#'onboarding_item_list']//a[@innertext='Cmt Mini Tornavida 31''li']", 30000, null, "995c9848-b564-40f8-96b7-36a6b08df2b3");
                _btnremoveInfo = new RepoItemInfo(this, "BtnRemove", ".//section[#'onboarding_item_list']/div[2]/ul/li/div[1]/div[2]/div[2]/div[2]/div[1]/div/a[1]/?/?/path", ".//section[#'onboarding_item_list']//li/div[1]/div[2]/div[2]/div[2]/div[1]/div/a[1]/svg/path", 30000, null, "90483106-88e6-4a0f-9c4e-e9f5dd1d272c");
                _removenotificationInfo = new RepoItemInfo(this, "RemoveNotification", "body/div[3]/div/div/div[2]/div[@innertext>'                        Ürün']", ".//div[@innertext>'                        Ürün']", 30000, null, "2215e182-2b94-46d3-ab75-2c035766ac47");
                _btnremove2Info = new RepoItemInfo(this, "BtnRemove2", ".//section[#'onboarding_item_list']/div[2]/ul/li/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div/div/div/div/button[@innertext='Sil']", ".//section[#'onboarding_item_list']//button[@innertext='Sil']", 30000, null, "3776859a-29ac-4582-8396-87bbfa7b0883");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("37fb3645-05db-4947-9adc-5cfd4647ea85")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("37fb3645-05db-4947-9adc-5cfd4647ea85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemName item.
            /// </summary>
            [RepositoryItem("995c9848-b564-40f8-96b7-36a6b08df2b3")]
            public virtual Ranorex.ATag ItemName
            {
                get
                {
                    return _itemnameInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ItemName item info.
            /// </summary>
            [RepositoryItemInfo("995c9848-b564-40f8-96b7-36a6b08df2b3")]
            public virtual RepoItemInfo ItemNameInfo
            {
                get
                {
                    return _itemnameInfo;
                }
            }

            /// <summary>
            /// The BtnRemove item.
            /// </summary>
            [RepositoryItem("90483106-88e6-4a0f-9c4e-e9f5dd1d272c")]
            public virtual Ranorex.PathTag BtnRemove
            {
                get
                {
                    return _btnremoveInfo.CreateAdapter<Ranorex.PathTag>(true);
                }
            }

            /// <summary>
            /// The BtnRemove item info.
            /// </summary>
            [RepositoryItemInfo("90483106-88e6-4a0f-9c4e-e9f5dd1d272c")]
            public virtual RepoItemInfo BtnRemoveInfo
            {
                get
                {
                    return _btnremoveInfo;
                }
            }

            /// <summary>
            /// The RemoveNotification item.
            /// </summary>
            [RepositoryItem("2215e182-2b94-46d3-ab75-2c035766ac47")]
            public virtual Ranorex.DivTag RemoveNotification
            {
                get
                {
                    return _removenotificationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RemoveNotification item info.
            /// </summary>
            [RepositoryItemInfo("2215e182-2b94-46d3-ab75-2c035766ac47")]
            public virtual RepoItemInfo RemoveNotificationInfo
            {
                get
                {
                    return _removenotificationInfo;
                }
            }

            /// <summary>
            /// The BtnRemove2 item.
            /// </summary>
            [RepositoryItem("3776859a-29ac-4582-8396-87bbfa7b0883")]
            public virtual Ranorex.ButtonTag BtnRemove2
            {
                get
                {
                    return _btnremove2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnRemove2 item info.
            /// </summary>
            [RepositoryItemInfo("3776859a-29ac-4582-8396-87bbfa7b0883")]
            public virtual RepoItemInfo BtnRemove2Info
            {
                get
                {
                    return _btnremove2Info;
                }
            }
        }

        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("3c62336d-dc6d-4b37-80ae-342503924fd0")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _errornotificationInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/dom[@domain='giris.hepsiburada.com']", parentFolder, 30000, null, false, "3c62336d-dc6d-4b37-80ae-342503924fd0", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", ".//input[#'txtUserName']", ".//input[#'txtUserName']", 30000, null, "af99ac3c-2b5e-4235-8b1b-f8eb044a01ec");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[2]//form[@action='https://giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3D36b0358c3cbf401bb0710a5af75c8018%26code_challenge%3D2m-th7U7KFux4xzyJ5LX4EHje0ltiGM4huJqbCuYKQM%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DPURE_LOGIN%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F']/div[2]/?/?/input[@id='txtPassword']", ".//input[#'txtPassword']", 30000, null, "8801b773-d9fc-4f2d-a806-bba2ebef0613");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//button[#'btnLogin']", ".//button[#'btnLogin']", 30000, null, "a6f03664-aa30-44fe-b837-8d496b17608c");
                _errornotificationInfo = new RepoItemInfo(this, "ErrorNotification", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[2]/div/div/div/div/div/div/div[1]/div[@innertext>'Girdiğiniz şifre eksik veya']", ".//div[#'root']//div[@innertext>'Girdiğiniz şifre eksik veya']", 30000, null, "d7cf978f-d8bb-4b5b-9e12-05dabccf956f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3c62336d-dc6d-4b37-80ae-342503924fd0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c62336d-dc6d-4b37-80ae-342503924fd0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("af99ac3c-2b5e-4235-8b1b-f8eb044a01ec")]
            public virtual Ranorex.InputTag TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("af99ac3c-2b5e-4235-8b1b-f8eb044a01ec")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("8801b773-d9fc-4f2d-a806-bba2ebef0613")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("8801b773-d9fc-4f2d-a806-bba2ebef0613")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("a6f03664-aa30-44fe-b837-8d496b17608c")]
            public virtual Ranorex.ButtonTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("a6f03664-aa30-44fe-b837-8d496b17608c")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The ErrorNotification item.
            /// </summary>
            [RepositoryItem("d7cf978f-d8bb-4b5b-9e12-05dabccf956f")]
            public virtual Ranorex.DivTag ErrorNotification
            {
                get
                {
                    return _errornotificationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorNotification item info.
            /// </summary>
            [RepositoryItemInfo("d7cf978f-d8bb-4b5b-9e12-05dabccf956f")]
            public virtual RepoItemInfo ErrorNotificationInfo
            {
                get
                {
                    return _errornotificationInfo;
                }
            }
        }

        /// <summary>
        /// The ReloadLoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("2e9fd513-b0d0-4a2d-a5b4-5093b8b17379")]
        public partial class ReloadLoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _reloadpageInfo;

            /// <summary>
            /// Creates a new ReloadLoginPage  folder.
            /// </summary>
            public ReloadLoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReloadLoginPage", "/form[@title>'Üye Giriş Sayfası & Üye Ol']", parentFolder, 30000, null, true, "2e9fd513-b0d0-4a2d-a5b4-5093b8b17379", "")
            {
                _reloadpageInfo = new RepoItemInfo(this, "ReloadPage", "container[@accessiblename>'Üye Giriş Sayfası & Üye Ol']/container/container[@accessiblerole='Pane']/container[2]/container[1]/toolbar[@accessiblerole='ToolBar']/?/?/button[@accessiblename='Yeniden Yükle']", ".//button[@accessiblename='Yeniden Yükle']", 30000, null, "17b1a0dd-ea22-499c-94ba-6fd087ba8169");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e9fd513-b0d0-4a2d-a5b4-5093b8b17379")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e9fd513-b0d0-4a2d-a5b4-5093b8b17379")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReloadPage item.
            /// </summary>
            [RepositoryItem("17b1a0dd-ea22-499c-94ba-6fd087ba8169")]
            public virtual Ranorex.Button ReloadPage
            {
                get
                {
                    return _reloadpageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReloadPage item info.
            /// </summary>
            [RepositoryItemInfo("17b1a0dd-ea22-499c-94ba-6fd087ba8169")]
            public virtual RepoItemInfo ReloadPageInfo
            {
                get
                {
                    return _reloadpageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
