///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HBTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoveFromCart recording.
    /// </summary>
    [TestModule("39c27080-fcd5-4bee-9822-d88ba66296d0", ModuleType.Recording, 1)]
    public partial class RemoveFromCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HBTestRepository repository.
        /// </summary>
        public static HBTestRepository repo = HBTestRepository.Instance;

        static RemoveFromCart instance = new RemoveFromCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoveFromCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoveFromCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CartPage.BtnRemove' at 5;2.", repo.CartPage.BtnRemoveInfo, new RecordItemIndex(0));
            repo.CartPage.BtnRemove.Click("5;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CartPage.BtnRemove2' at 171;22.", repo.CartPage.BtnRemove2Info, new RecordItemIndex(1));
            repo.CartPage.BtnRemove2.Click("171;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                        Ürün sepetinizden kaldırıldı\n                    ') on item 'CartPage.RemoveNotification'.", repo.CartPage.RemoveNotificationInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.CartPage.RemoveNotificationInfo, "InnerText", "\n                        Ürün sepetinizden kaldırıldı\n                    ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
