///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HBTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchingItem recording.
    /// </summary>
    [TestModule("132cd6b7-b9e7-4b7d-b40f-d4e4b958b935", ModuleType.Recording, 1)]
    public partial class SearchingItem : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HBTestRepository repository.
        /// </summary>
        public static HBTestRepository repo = HBTestRepository.Instance;

        static SearchingItem instance = new SearchingItem();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchingItem()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchingItem Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainPage.SearchingItem.SearchBox' at 273;27.", repo.MainPage.SearchingItem.SearchBoxInfo, new RecordItemIndex(1));
            repo.MainPage.SearchingItem.SearchBox.Click("273;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 700ms.", new RecordItemIndex(2));
            Delay.Duration(700, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tornavida' with focus on 'MainPage'.", repo.MainPage.SelfInfo, new RecordItemIndex(3));
            repo.MainPage.Self.EnsureVisible();
            Keyboard.Press("tornavida");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainPage.SearchingItem.btnARA' at 19;26.", repo.MainPage.SearchingItem.btnARAInfo, new RecordItemIndex(4));
            repo.MainPage.SearchingItem.btnARA.Click("19;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainPage.SearchingItem.ItemLink' at 110;8.", repo.MainPage.SearchingItem.ItemLinkInfo, new RecordItemIndex(6));
            repo.MainPage.SearchingItem.ItemLink.Click("110;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n        Cmt Mini Tornavida 31'li\n    ') on item 'MainPage.SearchingItem.ProductName'.", repo.MainPage.SearchingItem.ProductNameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.MainPage.SearchingItem.ProductNameInfo, "InnerText", "\n        Cmt Mini Tornavida 31'li\n    ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
